name: Quaesitus
favicon: null
layout_spectrum: 0.26299443026073277
typography_spectrum: 0.4751122109591961
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.44633095036260784
  lightness: 0.27108118683099747
  saturation: 0.2043142335023731
  rhythmicContrast: 0.17846454656682909
purpose: []
