name: Quaesitus
favicon: null
layout_spectrum: 0.48741
typography_spectrum: 0.75189
title: Quaesitus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f37652'
    - '#f9b9a6'
    - '#ffffff'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
